import http from 'node:http'
import fs from 'node:fs/promises'
import path from 'node:path'
import crypto from 'node:crypto'
import zlib from 'node:zlib'
import { fileURLToPath } from 'node:url'

const root = path.dirname(fileURLToPath(import.meta.url))
const appRoot = path.resolve(root, '..')
const staticRoot = path.join(appRoot, 'ui')
const dataRoot = path.resolve(process.env.TRIM_PKGVAR || path.resolve(appRoot, '../../.appdata'), 'SimpleMindMap')
const port = Number(process.env.PORT || 3000)
const socketPath = process.env.SIMPLEMINDMAP_SOCKET || path.join(process.env.TRIM_APPDEST || appRoot, 'app.sock')
const base = '/app/SimpleMindMap'
const allowed = new Set(['smm', 'json', 'xmind', 'md', 'xlsx'])
const mime = { '.html': 'text/html; charset=utf-8', '.js': 'application/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8', '.svg': 'image/svg+xml', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.ico': 'image/x-icon', '.woff': 'font/woff', '.woff2': 'font/woff2', '.ttf': 'font/ttf' }
const user = req => { const uid = String(req.headers['x-trim-userid'] || '').trim(); return uid ? { uid, username: String(req.headers['x-trim-username'] || '飞牛用户') } : null }
const externalPath = value => { const raw = String(value || '').replaceAll('\\', '/'); if (!raw.startsWith('/') || raw.includes('\0')) throw Error('invalid_external_path'); const clean = path.posix.normalize(raw); if (clean === '/' || clean.includes('/../') || path.posix.extname(clean) === '') throw Error('invalid_external_path'); if (!allowed.has(path.posix.extname(clean).slice(1).toLowerCase())) throw Error('unsupported_extension'); return clean }
const trimApi = (reqName, data) => new Promise((resolve, reject) => { const socket = process.env.TRIM_OPEN_API_SOCKET || '/var/run/trim_open_gateway_apiscope.socket'; const body = JSON.stringify({ reqId: crypto.randomUUID(), req: reqName, appName: 'SimpleMindMap', data }); const request = http.request({ socketPath: socket, path: '/api/v1/trimapp', method: 'POST', headers: { 'content-type': 'application/json', 'content-length': Buffer.byteLength(body), authorization: `Bearer ${process.env.TRIM_API_TOKEN || ''}` } }, response => { const chunks = []; response.on('data', c => chunks.push(c)); response.on('end', () => { try { const parsed = JSON.parse(Buffer.concat(chunks).toString()); if (parsed.code !== undefined && parsed.code !== 0) throw Error(parsed.msg || 'trim_api_failed'); resolve(parsed.data ?? parsed.result ?? parsed) } catch (error) { reject(error) } }) }); request.on('error', reject); request.end(body) })
const rel = value => { const raw = String(value || '').replaceAll('\\', '/').replace(/^\/+/, ''); const clean = path.posix.normalize(raw); if (!raw || clean === '.' || clean.startsWith('../') || clean.includes('/../')) throw Error('invalid_path'); return clean }
const target = (u, value, file = false) => { const clean = rel(value); if (file && !allowed.has(path.extname(clean).slice(1).toLowerCase())) throw Error('unsupported_extension'); const out = path.resolve(dataRoot, u.uid, clean); if (!out.startsWith(path.resolve(dataRoot, u.uid) + path.sep)) throw Error('invalid_path'); return out }
const parseBody = req => new Promise((resolve, reject) => { const chunks = []; req.on('data', c => chunks.push(c)); req.on('end', () => { try { resolve(JSON.parse(Buffer.concat(chunks).toString() || '{}')) } catch (e) { reject(e) } }); req.on('error', reject) })
const send = (res, status, value, headers = {}) => { const binary = Buffer.isBuffer(value); const body = binary ? value : Buffer.from(typeof value === 'string' ? value : JSON.stringify(value)); res.writeHead(status, { 'content-type': headers['content-type'] || (binary ? 'application/octet-stream' : 'application/json; charset=utf-8'), 'content-length': body.length, ...headers }); res.end(body) }
const tree = async (dir, prefix = '') => { const out = []; for (const item of await fs.readdir(dir, { withFileTypes: true })) { const p = prefix ? `${prefix}/${item.name}` : item.name; if (item.isDirectory()) out.push({ type: 'folder', name: item.name, path: p, children: await tree(path.join(dir, item.name), p) }); else if (item.name !== '.recent.json') out.push({ type: 'file', name: item.name, path: p }) } return out }
const recentPath = u => path.join(dataRoot, u.uid, '.recent.json')
const crcTable = (() => { const t = new Uint32Array(256); for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; t[n] = c >>> 0 } return t })()
const crc32 = data => { let c = 0xffffffff; for (const b of data) c = crcTable[(c ^ b) & 0xff] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0 }
const zip = async (dir, prefix = '') => { const files = []; const walk = async (current, name) => { for (const item of await fs.readdir(current, { withFileTypes: true })) { if (item.name === '.recent.json') continue; const next = name ? `${name}/${item.name}` : item.name; const disk = path.join(current, item.name); if (item.isDirectory()) await walk(disk, next); else files.push({ name: next, data: await fs.readFile(disk) }) } }; await walk(dir, prefix); const locals = []; const central = []; let offset = 0; for (const file of files) { const name = Buffer.from(file.name); const crc = crc32(file.data); const local = Buffer.alloc(30); local.writeUInt32LE(0x04034b50, 0); local.writeUInt16LE(20, 4); local.writeUInt32LE(crc, 14); local.writeUInt32LE(file.data.length, 18); local.writeUInt32LE(file.data.length, 22); local.writeUInt16LE(name.length, 26); const record = Buffer.concat([local, name, file.data]); locals.push(record); const header = Buffer.alloc(46); header.writeUInt32LE(0x02014b50, 0); header.writeUInt16LE(20, 4); header.writeUInt16LE(20, 6); header.writeUInt32LE(crc, 16); header.writeUInt32LE(file.data.length, 20); header.writeUInt32LE(file.data.length, 24); header.writeUInt16LE(name.length, 28); header.writeUInt32LE(offset, 42); central.push(Buffer.concat([header, name])); offset += record.length } const centralData = Buffer.concat(central); const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(files.length, 8); end.writeUInt16LE(files.length, 10); end.writeUInt32LE(centralData.length, 12); end.writeUInt32LE(offset, 16); return Buffer.concat([...locals, centralData, end]) }
const unzip = archive => { const end = archive.lastIndexOf(Buffer.from([0x50, 0x4b, 0x05, 0x06])); if (end < 0) throw Error('invalid_zip'); const count = archive.readUInt16LE(end + 10); let offset = archive.readUInt32LE(end + 16); const files = []; for (let i = 0; i < count; i++) { if (archive.readUInt32LE(offset) !== 0x02014b50) throw Error('invalid_zip'); const method = archive.readUInt16LE(offset + 10); const compressedSize = archive.readUInt32LE(offset + 20); const size = archive.readUInt32LE(offset + 24); const nameLength = archive.readUInt16LE(offset + 28); const extraLength = archive.readUInt16LE(offset + 30); const commentLength = archive.readUInt16LE(offset + 32); const localOffset = archive.readUInt32LE(offset + 42); const name = archive.subarray(offset + 46, offset + 46 + nameLength).toString('utf8'); offset += 46 + nameLength + extraLength + commentLength; if (!name || name.endsWith('/')) continue; const clean = rel(name); if (!allowed.has(path.extname(clean).slice(1).toLowerCase())) throw Error('unsupported_extension'); if (archive.readUInt32LE(localOffset) !== 0x04034b50) throw Error('invalid_zip'); const localNameLength = archive.readUInt16LE(localOffset + 26); const localExtraLength = archive.readUInt16LE(localOffset + 28); const input = archive.subarray(localOffset + 30 + localNameLength + localExtraLength, localOffset + 30 + localNameLength + localExtraLength + compressedSize); const data = method === 0 ? input : method === 8 ? zlib.inflateRawSync(input) : (() => { throw Error('unsupported_zip_compression') })(); if (data.length !== size || data.length > 20 * 1024 * 1024) throw Error('invalid_zip'); files.push({ path: clean, data }) } return files }
const server = http.createServer(async (req, res) => {
  try { const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`)
    if (url.pathname.startsWith(`${base}/api/`)) { const api = url.pathname.slice(`${base}/api/`.length)
      if (api === 'external/file') { const source = externalPath(url.searchParams.get('path')); if (req.method === 'GET') return send(res, 200, await fs.readFile(source), { 'cache-control': 'no-store', 'x-content-type-options': 'nosniff' }); if (req.method === 'PUT') { const d = await parseBody(req); const temp = path.join(path.dirname(source), `.${path.basename(source)}.simplemindmap-${crypto.randomUUID()}.tmp`); try { await fs.writeFile(temp, Buffer.from(d.content || '', 'base64'), { flag: 'wx', mode: 0o600 }); await fs.rename(temp, source) } finally { await fs.rm(temp, { force: true }).catch(() => {}) } return send(res, 200, { ok: true }) } }
      const u = user(req); if (!u) return send(res, 401, { error: 'login_required' }); await fs.mkdir(path.join(dataRoot, u.uid), { recursive: true });
      if (api === 'session') return send(res, 200, { user: u }); if (api === 'tree') { const requested = url.searchParams.get('path') || ''; const dir = requested ? target(u, requested) : path.join(dataRoot, u.uid); return send(res, 200, { tree: await tree(dir, requested) }) }
      if (api === 'recent' && req.method === 'GET') { let items = []; try { items = JSON.parse(await fs.readFile(recentPath(u), 'utf8')) } catch {} return send(res, 200, { items }) }
      if (api === 'recent' && req.method === 'POST') { const d = await parseBody(req); let items = []; try { items = JSON.parse(await fs.readFile(recentPath(u), 'utf8')) } catch {} const external = d.externalPath ? externalPath(d.externalPath) : ''; const entry = external ? { path: external, name: d.name || path.basename(external), external: true, openedAt: Date.now() } : { path: rel(d.path), name: d.name || path.basename(d.path), openedAt: Date.now() }; const next = [entry, ...items.filter(item => !(item.path === entry.path && Boolean(item.external) === Boolean(entry.external)))].slice(0, 20); await fs.writeFile(recentPath(u), JSON.stringify(next), { mode: 0o600 }); return send(res, 200, { items: next }) } if (api === 'recent' && (req.method === 'DELETE' || req.method === 'PUT')) { if (req.method === 'DELETE') { const removePath = url.searchParams.get('path'); let items = []; try { items = JSON.parse(await fs.readFile(recentPath(u), 'utf8')) } catch {} const normalizedPath = removePath ? (String(removePath).startsWith('/') ? externalPath(removePath) : rel(removePath)) : ''; const next = removePath ? items.filter(x => x.path !== normalizedPath) : []; await fs.writeFile(recentPath(u), JSON.stringify(next), { mode: 0o600 }); return send(res, 200, { items: next }) } const d = await parseBody(req); let items = []; try { items = JSON.parse(await fs.readFile(recentPath(u), 'utf8')) } catch {} const oldPath = rel(d.oldPath); const next = items.map(x => x.path === oldPath ? { ...x, path: rel(d.path), name: d.name || path.basename(d.path) } : x); await fs.writeFile(recentPath(u), JSON.stringify(next), { mode: 0o600 }); return send(res, 200, { items: next }) }
      if (api === 'folders' && req.method === 'POST') { const d = await parseBody(req); const clean = rel(d.path); const p = target(u, clean); try { await fs.access(p); return send(res, 409, { error: 'name_taken', name: path.basename(clean) }) } catch {} await fs.mkdir(p, { recursive: false }); return send(res, 201, { path: clean }) }
      if (api === 'rename' && req.method === 'POST') { const d = await parseBody(req); const oldPath = rel(d.oldPath); const nextPath = rel(d.path); const oldTarget = target(u, oldPath); const nextTarget = target(u, nextPath); try { await fs.access(nextTarget); return send(res, 409, { error: 'name_taken', name: path.basename(nextPath) }) } catch {} await fs.rename(oldTarget, nextTarget); return send(res, 200, { path: nextPath }) }
      if (api === 'upload/inspect' && req.method === 'POST') { const d = await parseBody(req); const dir = d.targetPath ? target(u, d.targetPath) : path.join(dataRoot, u.uid); const items = []; for (const f of d.files || []) { const p = rel(f.relativePath || f.name); if (!allowed.has(path.extname(p).slice(1).toLowerCase())) continue; let conflict = false; try { await fs.access(path.resolve(dir, p)); conflict = true } catch {} items.push({ path: p, conflict }) } return send(res, 200, { items, conflicts: items.filter(item => item.conflict).length }) }
      if (api === 'upload' && req.method === 'POST') { const d = await parseBody(req); const dir = d.targetPath ? target(u, d.targetPath) : path.join(dataRoot, u.uid); await fs.mkdir(dir, { recursive: true }); const result = []; const skipped = []; for (const f of d.files || []) { const original = rel(f.relativePath || f.name); if (!allowed.has(path.extname(original).slice(1).toLowerCase())) continue; const action = (d.actions || {})[original]; const p = action && action.type === 'rename' ? rel(action.path) : original; const out = path.resolve(dir, p); if (!out.startsWith(path.resolve(dataRoot, u.uid) + path.sep)) throw Error('invalid_path'); try { await fs.access(out); if (action === 'skip') { skipped.push(original); continue } } catch {} await fs.mkdir(path.dirname(out), { recursive: true }); await fs.writeFile(out, Buffer.from(f.content || '', 'base64'), { flag: action === 'overwrite' ? 'w' : 'wx', mode: 0o600 }); result.push(p) } return send(res, 201, { files: result, skipped }) }
      if (api === 'backup/inspect' && req.method === 'POST') { const d = await parseBody(req); const files = unzip(Buffer.from(d.archive || '', 'base64')); const items = []; for (const file of files) { const out = target(u, file.path, true); let conflict = false; try { await fs.access(out); conflict = true } catch {} items.push({ path: file.path, size: file.data.length, conflict }) } return send(res, 200, { items, total: items.length, conflicts: items.filter(item => item.conflict).length }) }
      if (api === 'backup/restore' && req.method === 'POST') { const d = await parseBody(req); const files = unzip(Buffer.from(d.archive || '', 'base64')); const summary = { restored: 0, skipped: 0, renamed: 0, overwritten: 0 }; for (const file of files) { const action = (d.actions || {})[file.path] || 'skip'; let next = file.path; if (action === 'skip') { try { await fs.access(target(u, next, true)); summary.skipped++; continue } catch {} } if (typeof action === 'object' && action.type === 'rename') { next = rel(action.path); summary.renamed++ } const out = target(u, next, true); try { await fs.access(out); if (action === 'overwrite') summary.overwritten++; else { summary.skipped++; continue } } catch {} await fs.mkdir(path.dirname(out), { recursive: true }); await fs.writeFile(out, file.data, { flag: action === 'overwrite' ? 'w' : 'wx', mode: 0o600 }); summary.restored++ } return send(res, 200, { summary }) }
      if (api === 'download' && req.method === 'GET') { const requested = url.searchParams.get('path') || ''; const disk = requested ? target(u, requested) : path.join(dataRoot, u.uid); const info = await fs.stat(disk); if (!info.isDirectory()) return send(res, 400, { error: 'folder_required' }); const label = requested ? path.basename(requested) : 'SimpleMindMap'; const archive = await zip(disk, requested ? label : ''); const fileName = `${label}.zip`; return send(res, 200, archive, { 'content-type': 'application/zip', 'content-disposition': `attachment; filename*=UTF-8''${encodeURIComponent(fileName)}`, 'cache-control': 'no-store', 'x-content-type-options': 'nosniff' }) }
      const m = api.match(/^files\/(.+)$/); if (m) { const requested = decodeURIComponent(m[1]); const p = target(u, requested, req.method === 'GET' || req.method === 'PUT'); if (req.method === 'GET') return send(res, 200, await fs.readFile(p), { 'cache-control': 'no-store' }); if (req.method === 'PUT') { const d = await parseBody(req); const tmp = `${p}.${crypto.randomUUID()}.tmp`; await fs.writeFile(tmp, Buffer.from(d.content || '', 'base64'), { flag: 'wx', mode: 0o600 }); await fs.rename(tmp, p); return send(res, 200, { ok: true }) } if (req.method === 'DELETE') { await fs.rm(p, { recursive: true }); let items = []; try { items = JSON.parse(await fs.readFile(recentPath(u), 'utf8')) } catch {} const prefix = requested + '/'; await fs.writeFile(recentPath(u), JSON.stringify(items.filter(x => x.path !== requested && !x.path.startsWith(prefix))), { mode: 0o600 }); return send(res, 204, '') } }
      return send(res, 404, { error: 'not_found' }) }
    let file = url.pathname.startsWith(base) ? url.pathname.slice(base.length) : url.pathname; if (!file || file === '/') file = '/index.html'; const p = path.resolve(staticRoot, `.${file}`); if (!p.startsWith(staticRoot)) return send(res, 400, 'invalid_path'); const headers = { 'content-type': mime[path.extname(file).toLowerCase()] || 'application/octet-stream' }; return send(res, 200, await fs.readFile(p), headers)
  } catch (e) {
    const error = e.message || 'request_failed'
    send(res, error === 'file_access_denied' ? 403 : 400, { error })
  }
})
const listenTarget = process.platform === 'win32' ? { port, host: '0.0.0.0' } : socketPath
if (typeof listenTarget === 'string') { try { await fs.rm(listenTarget, { force: true }) } catch {} }
server.listen(listenTarget)
