<template>
  <div class="home">
    <aside class="sidebar">
      <h1>SimpleMindMap</h1><div class="user">👤 {{ username }}</div>
      <el-button type="primary" @click="newDocument">开始新建</el-button>
      <el-button type="success" @click="openUpload">上传文件/文件夹</el-button>
      <el-button plain @click="openLocal">打开本地文件</el-button>
      <input ref="localInput" type="file" accept=".smm,.json,.xmind,.md" hidden @change="localSelected">
      <input ref="uploadInput" type="file" accept=".smm,.json,.xmind,.md,.xlsx" multiple hidden @change="uploadFilesSelected">
      <input ref="folderInput" type="file" webkitdirectory directory multiple hidden @change="folderSelected">
    </aside>
    <main class="content">
      <div class="content-head"><h2>文件</h2></div>
      <el-tabs v-model="activeTab">
        <el-tab-pane label="最近打开" name="recent">
          <div class="tab-actions"><el-button size="small" @click="clearRecent">清除全部记录</el-button></div>
          <el-table :data="recent" size="small" empty-text="暂无最近打开的云端文件" @row-dblclick="openCloud">
            <el-table-column label="名称"><template slot-scope="s"><span class="file-name">{{ s.row.name }}</span></template></el-table-column><el-table-column prop="path" label="路径"/>
            <el-table-column label="操作" width="150"><template slot-scope="s"><el-button type="text" @click="openCloud(s.row)">打开</el-button><el-button type="text" class="danger" @click="clearOneRecent(s.row)">清除</el-button></template></el-table-column>
          </el-table>
        </el-tab-pane>
        <el-tab-pane label="云端文件" name="cloud">
          <div class="cloud-tools"><el-button icon="el-icon-folder-add" @click="openFolderDialog">新建文件夹</el-button><el-button icon="el-icon-upload2" @click="$refs.backupInput.click()">导入备份</el-button><el-input v-model="search" clearable prefix-icon="el-icon-search" placeholder="搜索文件夹或文件"/><el-button icon="el-icon-download" @click="downloadEntry({type:'folder',name:'根目录',path:''})">下载</el-button><el-button circle icon="el-icon-refresh" title="刷新文件结构" @click="refresh"></el-button><input ref="backupInput" type="file" accept=".zip,application/zip" hidden @change="inspectBackup"></div>
          <el-tree ref="cloudTree" :key="treeVersion" :data="filteredTree" node-key="path" :default-expanded-keys="displayExpandedKeys" :expand-on-click-node="false" :props="{label:'name',children:'children'}" class="tree" @node-click="handleNodeClick" @node-expand="rememberExpand" @node-collapse="rememberCollapse">
            <span slot-scope="{data}" class="tree-row" @dblclick.stop="handleEntryDblclick(data)"><span class="entry-label"><span class="entry-icon">{{ data.type === 'folder' ? '📁' : '📄' }}</span><span v-html="highlight(data.type === 'file' ? displayName(data.name) : data.name)"></span></span><span><el-button v-if="data.type === 'file'" type="text" @click.stop="openCloud(data)">打开</el-button><el-button type="text" @click.stop="downloadEntry(data)">下载</el-button><el-button type="text" @click.stop="renameEntry(data)">重命名</el-button><el-button type="text" class="danger" @click.stop="removeEntry(data)">删除</el-button></span></span>
          </el-tree>
        </el-tab-pane>
      </el-tabs>
    </main>
    <el-dialog title="上传文件/文件夹" :visible.sync="uploadOpen" width="560px"><div class="upload-actions"><el-button @click="chooseUploadFiles">选择文件</el-button><el-button @click="openLocalFolder">选择文件夹</el-button></div><div class="upload-list"><div v-for="(f,i) in pending" :key="f.relativePath+i" class="upload-item"><span>{{ f.relativePath }}</span><el-button type="text" @click="pending.splice(i,1)">删除</el-button></div><div v-if="!pending.length" class="empty">尚未选择文件</div></div><div class="path-row"><el-button size="small" icon="el-icon-folder-add" @click="openFolderDialog">新建文件夹</el-button><el-select v-model="targetPath" filterable clearable placeholder="请选择文件夹"><el-option v-for="folder in folderOptions" :key="folder.path" :label="folder.path" :value="folder.path"/></el-select></div><div class="upload-footer"><el-button @click="uploadOpen=false">取消</el-button><el-button type="primary" :disabled="!pending.length || !targetPath" @click="prepareUpload">确认上传</el-button></div></el-dialog>
    <el-dialog title="开始新建" :visible.sync="newOpen" width="460px"><el-form label-width="90px"><el-form-item label="文件名"><el-input v-model="newName" placeholder="例如：项目计划.smm"/></el-form-item><el-form-item label="保存位置"><div class="path-row"><el-button size="small" icon="el-icon-folder-add" @click="openFolderDialog">新建文件夹</el-button><el-select v-model="selectedNewFolder" filterable placeholder="请选择文件夹" style="flex:1"><el-option v-for="folder in folderOptions" :key="folder.path" :label="folder.path" :value="folder.path"/></el-select></div></el-form-item></el-form><span slot="footer"><el-button @click="newOpen=false">取消</el-button><el-button type="primary" :disabled="!newName || !selectedNewFolder" @click="createDocument">创建并编辑</el-button></span></el-dialog>
    <el-dialog title="新建文件夹" :visible.sync="folderOpen" width="460px"><el-form label-width="90px"><el-form-item label="文件夹名"><el-input v-model="folderName"/></el-form-item><el-form-item label="保存位置"><el-select v-model="parentFolder" filterable clearable placeholder="根目录或选择文件夹" style="width:100%"><el-option label="根目录" value=""/><el-option v-for="folder in allFolders" :key="folder.path" :label="folder.path" :value="folder.path"/></el-select></el-form-item></el-form><span slot="footer"><el-button @click="folderOpen=false">取消</el-button><el-button type="primary" :disabled="!folderName" @click="createFolder">确认</el-button></span></el-dialog>
    <el-dialog title="下载文件" :visible.sync="downloadFileOpen" width="420px"><p class="download-tip">选择导出文件格式</p><div class="download-types"><el-button v-for="type in downloadTypes" :key="type" @click="exportFile(type)">.{{ type }}</el-button></div><span slot="footer"><el-button @click="downloadFileOpen=false">取消</el-button></span></el-dialog>
    <el-dialog title="导入备份" :visible.sync="backupOpen" width="680px"><p v-if="backupSummary">共 {{ backupSummary.total }} 个文件，其中 {{ backupSummary.conflicts }} 个与云端文件重名。</p><div class="backup-list"><div v-for="item in backupItems" :key="item.path" class="backup-item"><span>{{ item.path }}</span><el-select v-if="item.conflict" v-model="backupActions[item.path]" size="mini"><el-option label="跳过" value="skip"/><el-option label="覆盖" value="overwrite"/><el-option label="重命名" value="rename"/></el-select><el-input v-if="backupActions[item.path] === 'rename'" v-model="backupRename[item.path]" size="mini" placeholder="新的完整路径"/></div></div><span slot="footer"><el-button @click="backupOpen=false">取消</el-button><el-button type="primary" :disabled="!backupItems.length" @click="restoreBackup">确认恢复</el-button></span></el-dialog>
    <el-dialog title="处理重名文件" :visible.sync="uploadConflictOpen" width="640px"><p>以下文件已存在，请逐项选择处理方式。</p><div class="backup-list"><div v-for="item in uploadConflictItems" :key="item.path" class="backup-item"><span>{{ item.path }}</span><el-select v-model="uploadActions[item.path]" size="mini"><el-option label="跳过" value="skip"/><el-option label="覆盖" value="overwrite"/><el-option label="重命名" value="rename"/></el-select><el-input v-if="uploadActions[item.path] === 'rename'" v-model="uploadRename[item.path]" size="mini" placeholder="新的文件名"/></div></div><span slot="footer"><el-button @click="uploadConflictOpen=false">取消</el-button><el-button type="primary" @click="performUpload">确认上传</el-button></span></el-dialog>
  </div>
</template>

<script>
export default {
  data: () => ({ username: '飞牛用户', tree: [], recent: [], activeTab: localStorage.getItem('simpleMindMapHomeTab') || 'recent', search: '', expandedPaths: [], treeVersion: 0, uploadOpen: false, pending: [], targetPath: '', newOpen: false, newName: '未命名.smm', selectedNewFolder: '', folderOpen: false, folderName: '', parentFolder: '', downloadFileOpen: false, downloadFile: null, downloadTypes: ['smm', 'json', 'xmind', 'md', 'txt', 'png', 'pdf'], backupOpen: false, backupArchive: '', backupItems: [], backupSummary: null, backupActions: {}, backupRename: {}, uploadConflictOpen: false, uploadFiles: [], uploadConflictItems: [], uploadActions: {}, uploadRename: {} }),
  computed: {
    allFolders() { const result = []; const walk = items => (items || []).forEach(item => { if (item.type === 'folder') { result.push(item); walk(item.children) } }); walk(this.tree); return result },
    folderOptions() { return this.allFolders },
    expandedKeys() { const q = this.search.trim().toLowerCase(); if (!q) return []; const keys = []; const walk = items => (items || []).forEach(item => { if (item.type === 'folder' && (item.children || []).some(child => this.hasMatch(child, q))) keys.push(item.path); walk(item.children) }); walk(this.tree); return keys },
    displayExpandedKeys() { return [...new Set([...this.expandedPaths, ...this.expandedKeys])] },
    filteredTree() { const q = this.search.trim().toLowerCase(); if (!q) return this.tree; const filter = items => (items || []).reduce((result, item) => { const own = item.name.toLowerCase().includes(q); const children = own ? item.children || [] : filter(item.children); if (own || children.length) result.push({ ...item, children }); return result }, []); return filter(this.tree) }
  },
  watch: { activeTab(value) { localStorage.setItem('simpleMindMapHomeTab', value) }, search() { this.treeVersion++ } },
  async created() { const session = await fetch('/app/SimpleMindMap/api/session').then(res => res.ok ? res.json() : null); if (!session) { location.href = '/login?redirect=' + encodeURIComponent(location.href); return } this.username = session.user.username; this.refresh() },
  methods: {
    displayName(name) { return String(name).replace(/\.[^.]+$/, '') },
    hasMatch(item, query) { return item.name.toLowerCase().includes(query) || (item.children || []).some(child => this.hasMatch(child, query)) },
    highlight(name) { const query = this.search.trim(); const safe = String(name).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); return query ? safe.replace(new RegExp(query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'ig'), match => `<strong class="search-hit">${match}</strong>`) : safe },
    rememberExpand(data) { if (!this.expandedPaths.includes(data.path)) this.expandedPaths.push(data.path) },
    rememberCollapse(data) { this.expandedPaths = this.expandedPaths.filter(path => path !== data.path) },
    handleNodeClick(data, node) { if (data.type === 'folder') { if (node.expanded) node.collapse(); else node.expand() } },
    handleEntryDblclick(data) { if (data.type === 'file') this.openCloud(data) },
    async refresh() { const [tree, recent] = await Promise.all([fetch('/app/SimpleMindMap/api/tree').then(res => res.json()), fetch('/app/SimpleMindMap/api/recent').then(res => res.json())]); this.tree = tree.tree || []; this.recent = recent.items || []; this.treeVersion++ },
    async downloadEntry(data) { if (data.type === 'folder') { if (!data.path) { try { await this.$confirm('是否将根目录下的全部文件下载为 ZIP？', '下载全部文件', { confirmButtonText: '下载 ZIP', cancelButtonText: '取消', type: 'warning' }) } catch (error) { return } } const anchor = document.createElement('a'); anchor.href = '/app/SimpleMindMap/api/download?path=' + encodeURIComponent(data.path || ''); anchor.download = (data.name || 'SimpleMindMap') + '.zip'; document.body.appendChild(anchor); anchor.click(); anchor.remove(); return } this.downloadFile = data; this.downloadFileOpen = true },
    exportFile(type) { if (!this.downloadFile) return; const file = this.downloadFile; this.downloadFileOpen = false; this.$router.push({ path: '/edit', query: { cloudPath: file.path, autoExport: '1', exportName: this.displayName(file.name), exportType: type } }) },
    async inspectBackup(event) { const file = event.target.files[0]; event.target.value = ''; if (!file) return; try { this.backupArchive = this.toBase64(new Uint8Array(await file.arrayBuffer())); const res = await fetch('/app/SimpleMindMap/api/backup/inspect', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ archive: this.backupArchive }) }); if (!res.ok) throw new Error(); const data = await res.json(); this.backupItems = data.items; this.backupSummary = data; this.backupActions = Object.fromEntries(data.items.filter(item => item.conflict).map(item => [item.path, 'skip'])); this.backupRename = {}; this.backupOpen = true } catch (error) { this.$message.error('备份文件无效或包含不支持的文件') } },
    async restoreBackup() { try { const actions = {}; Object.keys(this.backupActions).forEach(path => { actions[path] = this.backupActions[path] === 'rename' ? { type: 'rename', path: this.backupRename[path] || path } : this.backupActions[path] }); const res = await fetch('/app/SimpleMindMap/api/backup/restore', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ archive: this.backupArchive, actions }) }); if (!res.ok) throw new Error(); const data = await res.json(); this.backupOpen = false; await this.refresh(); const s = data.summary; this.$message.success(`恢复 ${s.restored} 个，覆盖 ${s.overwritten} 个，重命名 ${s.renamed} 个，跳过 ${s.skipped} 个`) } catch (error) { this.$message.error('恢复备份失败') } },
    newDocument() { this.newOpen = true; this.selectedNewFolder = ''; if (!this.folderOptions.length) this.$message.info('请先创建文件夹，再新建云端文件') },
    openFolderDialog() { this.folderName = ''; this.parentFolder = ''; this.folderOpen = true },
    async createFolder() { const path = this.parentFolder ? `${this.parentFolder}/${this.folderName}` : this.folderName; const res = await fetch('/app/SimpleMindMap/api/folders', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ path }) }); if (!res.ok) { const data = await res.json().catch(() => ({})); return this.$message.error(`新建失败：“${data.name || this.folderName}”名称已被占用`) } this.folderOpen = false; await this.refresh(); this.$message.success('文件夹已创建') },
    async createDocument() { if (!this.selectedNewFolder) return this.$message.warning('请选择保存文件夹'); const name = this.newName.toLowerCase().endsWith('.smm') ? this.newName : `${this.newName}.smm`; const path = `${this.selectedNewFolder}/${name}`; const data = { root: { data: { text: '中心主题' }, children: [] }, layout: 'logicalStructure', theme: { template: 'avocado', config: {} }, view: null, config: {} }; try { await this.uploadContent(this.selectedNewFolder, [{ name, relativePath: name, content: this.toBase64(JSON.stringify(data)) }]); await fetch('/app/SimpleMindMap/api/recent', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ path, name }) }); this.newOpen = false; this.$router.push({ path: '/edit', query: { cloudPath: path } }) } catch (error) { this.$message.error(`新建失败：“${name}”名称已被占用`) } },
    openUpload() { this.targetPath = ''; this.pending = []; this.uploadOpen = true },
    openLocal() { this.$refs.localInput.click() },
    openLocalFolder() { this.$refs.folderInput.click() },
    chooseUploadFiles() { this.$refs.uploadInput.click() },
    localSelected(event) { const file = event.target.files[0]; event.target.value = ''; if (!file) return; window.__simpleMindMapExternalPath = ''; window.__simpleMindMapLocalFile = file; this.$router.push({ path: '/edit', query: { localFile: '1', localName: file.name } }) },
    uploadFilesSelected(event) { this.pending = Array.from(event.target.files).map(file => ({ file, name: file.name, relativePath: file.name })); event.target.value = ''; this.uploadOpen = true },
    folderSelected(event) { this.pending = Array.from(event.target.files).map(file => ({ file, name: file.name, relativePath: file.name })); event.target.value = ''; this.uploadOpen = true },
    toBase64(value) { const bytes = typeof value === 'string' ? new TextEncoder().encode(value) : value; let binary = ''; for (let i = 0; i < bytes.length; i += 0x8000) binary += String.fromCharCode(...bytes.subarray(i, i + 0x8000)); return btoa(binary) },
    async uploadContent(targetPath, files, actions) { const res = await fetch('/app/SimpleMindMap/api/upload', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ targetPath, files, actions }) }); if (!res.ok) throw new Error('upload_failed') },
    async prepareUpload() { try { this.uploadFiles = []; for (const item of this.pending) this.uploadFiles.push({ name: item.name, relativePath: item.relativePath, content: this.toBase64(new Uint8Array(await item.file.arrayBuffer())) }); const res = await fetch('/app/SimpleMindMap/api/upload/inspect', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ targetPath: this.targetPath, files: this.uploadFiles }) }); if (!res.ok) throw new Error(); const data = await res.json(); this.uploadConflictItems = data.items.filter(item => item.conflict); if (this.uploadConflictItems.length) { this.uploadActions = Object.fromEntries(this.uploadConflictItems.map(item => [item.path, 'skip'])); this.uploadRename = {}; this.uploadConflictOpen = true } else this.performUpload() } catch (error) { this.$message.error('上传预检失败') } },
    async performUpload() { try { const actions = {}; Object.keys(this.uploadActions).forEach(path => { actions[path] = this.uploadActions[path] === 'rename' ? { type: 'rename', path: this.uploadRename[path] || path } : this.uploadActions[path] }); await this.uploadContent(this.targetPath, this.uploadFiles, actions); this.pending = []; this.uploadOpen = false; this.uploadConflictOpen = false; await this.refresh(); this.$message.success('上传完成') } catch (error) { this.$message.error('上传失败') } },
    async openCloud(row) { const externalPath = row.external ? row.path : ''; window.__simpleMindMapExternalPath = externalPath || ''; await fetch('/app/SimpleMindMap/api/recent', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(externalPath ? { externalPath, name: row.name } : { path: row.path, name: row.name }) }); this.$router.push({ path: '/edit', query: externalPath ? { path: externalPath } : { cloudPath: row.path } }) },
    async clearRecent() { await fetch('/app/SimpleMindMap/api/recent', { method: 'DELETE' }); this.recent = [] },
    async clearOneRecent(row) { const res = await fetch('/app/SimpleMindMap/api/recent?path=' + encodeURIComponent(row.path), { method: 'DELETE' }); this.recent = (await res.json()).items || [] },
    async renameEntry(data) { try { const { value } = await this.$prompt('请输入新名称', '重命名', { inputValue: data.name }); if (!value || value === data.name) return; const parent = data.path.includes('/') ? data.path.slice(0, data.path.lastIndexOf('/')) : ''; const path = parent ? `${parent}/${value}` : value; const res = await fetch('/app/SimpleMindMap/api/rename', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ oldPath: data.path, path }) }); if (!res.ok) return this.$message.error(`重命名失败：“${value}”名称已被占用`); await fetch('/app/SimpleMindMap/api/recent', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ oldPath: data.path, path, name: value }) }); await this.refresh(); this.$message.success('重命名成功') } catch (error) {} },
    async removeEntry(data) { try { await this.$confirm(`确定删除“${data.name}”吗？`, '删除确认', { type: 'warning' }); const res = await fetch('/app/SimpleMindMap/api/files/' + encodeURIComponent(data.path), { method: 'DELETE' }); if (!res.ok) throw new Error(); await this.refresh(); this.$message.success('已删除') } catch (error) {} }
  }
}
</script>

<style scoped>
.home{display:flex;height:100vh;background:#f4f6f8;color:#243447}.sidebar{width:250px;padding:28px 20px;background:#fff;border-right:1px solid #e5e9ef}.sidebar h1{font-size:20px;margin:0 0 12px}.user{color:#6b7785;margin-bottom:24px}.sidebar .el-button{width:100%;margin:0 0 12px}.content{flex:1;padding:36px 48px;overflow:auto}.content-head{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #dfe5ec;padding-bottom:18px}.content-head h2{margin:0}.tab-actions{display:flex;justify-content:flex-end;margin:12px 0}.cloud-tools{display:flex;align-items:center;gap:12px;margin:14px 0}.cloud-tools .el-input{flex:1;min-width:160px;max-width:520px}.cloud-tools .el-button{flex-shrink:0}.tree{background:#fff;padding:14px 18px;border:1px solid #e4eaf1;border-radius:6px;box-shadow:0 2px 8px rgba(31,45,61,.04)}.tree-row{display:flex;align-items:center;justify-content:space-between;gap:16px;width:100%;min-width:0;padding-right:12px}.entry-label{user-select:none;display:flex;align-items:center;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.entry-icon{display:inline-flex;align-items:center;justify-content:center;width:20px;height:20px;margin-right:5px;line-height:1;font-size:16px;flex:0 0 20px}.tree-row>span:last-child{display:flex;align-items:center;justify-content:flex-end;min-width:190px;flex-shrink:0}.tree-row .el-button{margin-left:10px}.tree-row .el-button+.el-button{margin-left:10px}.file-name{user-select:none}.danger{color:#f56c6c}.download-tip{margin:0 0 16px;color:#606266}.download-types{display:flex;flex-wrap:wrap;gap:10px}.download-types .el-button{margin:0;width:82px}.backup-list{max-height:340px;overflow:auto;border:1px solid #e5e9ef}.backup-item{display:flex;align-items:center;gap:10px;padding:9px 12px;border-bottom:1px solid #eef1f5}.backup-item>span{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.backup-item .el-select{width:92px;flex-shrink:0}.backup-item .el-input{width:180px;flex-shrink:0}.upload-actions{display:flex;gap:12px}.upload-list{height:240px;overflow:auto;border:1px solid #e5e9ef;margin:18px 0;padding:8px}.upload-item{display:flex;justify-content:space-between;padding:8px;border-bottom:1px solid #f0f2f5}.empty{text-align:center;color:#9aa5b1;padding:80px 0}.path-row{display:flex;align-items:center;gap:12px}.path-row .el-select{flex:1}.upload-footer{display:flex;justify-content:flex-end;gap:12px;margin-top:18px}::v-deep .search-hit{font-weight:700;background:#fff4a8;border-radius:2px;padding:0 1px}::v-deep .el-tree-node__content{height:36px;border-radius:4px}::v-deep .el-tree-node__content:hover{background:#f1f6ff}
@media (max-width:700px){.home{display:block;height:100dvh}.sidebar{position:fixed;z-index:10;bottom:0;left:0;right:0;width:auto;display:flex;align-items:stretch;gap:8px;padding:8px 10px calc(8px + env(safe-area-inset-bottom));border-top:1px solid #dfe5ec;border-right:0;box-shadow:0 -3px 14px rgba(15,23,42,.1)}.sidebar h1,.sidebar .user{display:none}.sidebar .el-button{flex:1;width:auto;min-width:0;height:44px;margin:0;padding:0 6px;font-size:12px;white-space:normal}.content{height:100%;padding:20px 14px 92px}.content-head{padding-bottom:12px}.cloud-tools{display:grid;grid-template-columns:1fr auto auto;gap:8px}.cloud-tools .el-input{grid-column:1 / -1;grid-row:1;max-width:none;width:100%;min-width:0}.cloud-tools .el-button{font-size:12px;padding:9px 10px}.tree{padding:8px}.tree-row{gap:4px;padding-right:4px}.tree-row>span:last-child{min-width:0;gap:0}.tree-row .el-button,.tree-row .el-button+.el-button{margin-left:4px;padding:6px 3px;font-size:12px}.entry-label{max-width:calc(100vw - 154px)}.upload-list{height:calc(100dvh - 390px);min-height:150px}.backup-list{max-height:calc(100dvh - 310px)}.backup-item{align-items:flex-start;flex-wrap:wrap}.backup-item .el-input{width:100%}.path-row{gap:8px}.path-row .el-select{min-width:0}::v-deep .el-dialog{width:calc(100vw - 28px)!important;margin-top:8vh!important}::v-deep .el-dialog__body{padding:18px 16px}::v-deep .el-dialog__footer{padding:10px 16px}::v-deep .el-form-item__label{float:none;width:auto!important;display:block;text-align:left}::v-deep .el-form-item__content{margin-left:0!important}}
@media (max-width:700px){
  .cloud-tools{grid-template-columns:repeat(4,minmax(0,1fr));}
  .cloud-tools .el-input{grid-column:1 / -1;grid-row:1;}
  ::v-deep .cloud-tools .el-button{width:100%;min-width:0;margin:0;font-size:11px;padding:9px 2px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}
  ::v-deep .cloud-tools .el-button.is-circle{border-radius:4px;}
  ::v-deep .el-message-box{width:calc(100vw - 28px)!important;max-width:none;}
  ::v-deep .el-message-box__btns{display:flex;flex-wrap:wrap;gap:8px;padding-top:8px;}
  ::v-deep .el-message-box__btns .el-button{flex:1;min-width:82px;margin:0;}
}
</style>
